name: Continous Integration

on:
  pull_request:
    types: [closed]
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout # checkout the repository
      uses: actions/checkout@main
      with:
        ref: main

    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:  
        username: 'root'   #ssh user name
        server: '35.240.131.231' #引用之前创建好的secret
        ssh_private_key: ${{secrets.document}} # linux的ssh_key设置在该项目中时所取的名字
        local_path: './build/*'  # 项目build的文件夹路径
        remote_path: '/usr/local/pe_projects/Equity-Document/'
